# Generated by Django 4.2.2 on 2023-07-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
