# Generated by Django 4.2.2 on 2023-07-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_fact_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.TextField(default='', max_length=255),
        ),
    ]
